# Generated by Django 5.0 on 2024-05-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cart_table'),
        ('product', '0002_carttable'),
    ]

    operations = [
    ]
